version: 2
updates:
- package-ecosystem: npm
  directory: "/cdk"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@aws-cdk/assert"
    versions:
    - "> 1.68.0"
  - dependency-name: jest
    versions:
    - "> 26.6.0"
  - dependency-name: ts-jest
    versions:
    - "> 26.4.1"
  - dependency-name: "@types/jest"
    versions:
    - "> 26.0.14"
  - dependency-name: "@types/node"
    versions:
    - "> 14.14.10"
  - dependency-name: monocdk
    versions:
    - 1.85.0
    - 1.87.1
  - dependency-name: aws-cdk
    versions:
    - 1.85.0
    - 1.87.1
  - dependency-name: typescript
    versions:
    - 4.1.3
- package-ecosystem: gomod
  directory: "/lambda"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
